# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# rbenv
# export PATH=~/.rbenv/shims:/usr/local/bin:/usr/bin:/bin
export PATH=~/.rbenv/shims:$PATH

export EDITOR='atom --wait'

# yarn
# export PATH="$PATH:`yarn global bin`"


# Random giglgglglge
alias random_giggle="node $HOME/dotfiles/script/random_giggle.js"

# ZSH Config
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
source "$HOME/.zsh/themes/itg-text.zsh-theme"
unsetopt AUTO_CD

# load zgen
source "${HOME}/.zgen/zgen.zsh"
if ! zgen save; then
  echo "Creating a zgen save"
  zgen prezto
  zgen prezto git
  zgen prezto command-not-found
  zgen prezto syntax-highlighting
  zgen prezto zsh-users/zsh-completions src
fi

# zsh modules
rm -f ~/.zcompdump; compinit

# Aliases
source $HOME/.aliases

DEFAULT_USER="🐻"

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$DEFAULT_USER"
  fi
}


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
