#RUBIES=(/Users/gomezelom/.rubies/rub*)
#source /usr/local/share/chruby/chruby.sh
#source /usr/local/share/chruby/auto.sh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# use atom as default editor
export EDITOR="/usr/local/bin/atom --wait"

# rbenv
# export PATH=~/.rbenv/shims:/usr/local/bin:/usr/bin:/bin
export PATH=~/.rbenv/shims:$PATH

# brew paths
export PATH=$PATH:/usr/local/sbin

# yarn
# export PATH="$PATH:`yarn global bin`"

alias gollum="ssh deployer@ec2-54-68-156-172.us-west-2.compute.amazonaws.com"
alias death_eaters="ssh deployer@ec2-52-40-170-84.us-west-2.compute.amazonaws.com"
alias gollum_db="psql -U deployer -h gollum-database.c5j9f1hequ4g.us-west-2.rds.amazonaws.com -p 5432 gollum_production"

# Random giglgglglge
alias random_giggle="node $HOME/dotfiles/script/random_giggle.js"

# ZSH Config
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt AUTO_CD

# load zgen
source "${HOME}/.zgen/zgen.zsh"
if ! zgen save; then
  echo "Creating a zgen save"
  zgen prezto
  zgen prezto git
  zgen prezto command-not-found
  zgen prezto syntax-highlighting
  zgen prezto zsh-users/zsh-completions src
fi

# zsh modules
rm -f ~/.zcompdump; compinit

# Aliases
source $HOME/.aliases

# use prompt pure
# https://github.com/sindresorhus/pure
autoload -U promptinit; promptinit
prompt pure

# autojump config
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
