#!/bin/bash

DOTFILES_ROOT="${HOME}/.dotfiles"
DOTFILES_REPO="git@github.com:no-itsbackpack/dotfiles.git"

if [[ ! -d ${DOTFILES_ROOT} ]]; then
  git clone ${DOTFILES_REPO} ${DOTFILES_ROOT}
fi

cd ${DOTFILES_ROOT}

# zsh
brew install zsh

# zprezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# zgen
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

# symlink files
script/bootstrap

# switch shell to zsh
if [ $SHELL != '/bin/zsh' ]; then
	chsh -s /bin/zsh
fi
